package com.ali.smartgarden.activities;

import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.lifecycle.ViewModelProvider;
import com.ali.smartgarden.R;
import com.ali.smartgarden.models.WeatherDay;
import com.ali.smartgarden.models.WeatherForecast;
import com.ali.smartgarden.views.WeatherTemperatureChartView;
import com.ali.smartgarden.viewmodels.MainViewModel;
import java.time.LocalDate; import java.time.format.DateTimeFormatter; import java.util.List; import java.util.Locale;

public class WeatherForecastActivity extends AppCompatActivity {
 private TextView location,deviceLocation,temp,condition,details,humidity,wind,rain,pressure,advice; private ImageView icon; private LinearLayout days,insights; private WeatherTemperatureChartView chart;
 @Override public void onCreate(Bundle s){super.onCreate(s);setContentView(R.layout.activity_weather_forecast);findViewById(R.id.btnWeatherBack).setOnClickListener(v->finish());findViewById(R.id.btnWeatherLocationSettings).setOnClickListener(v->startActivity(new Intent(this,GardenLocationActivity.class))); location=findViewById(R.id.txtWeatherLocation);deviceLocation=findViewById(R.id.txtWeatherDeviceLocation);temp=findViewById(R.id.txtWeatherCurrentTemp);condition=findViewById(R.id.txtWeatherCurrentCondition);details=findViewById(R.id.txtWeatherCurrentDetails);humidity=findViewById(R.id.txtWeatherMetricHumidity);wind=findViewById(R.id.txtWeatherMetricWind);rain=findViewById(R.id.txtWeatherMetricRain);pressure=findViewById(R.id.txtWeatherMetricPressure);advice=findViewById(R.id.txtWeatherAdvice);icon=findViewById(R.id.imgWeatherCurrent);days=findViewById(R.id.layoutWeatherDays);insights=findViewById(R.id.layoutWeatherInsights);chart=findViewById(R.id.chartWeatherTemperature);new ViewModelProvider(this).get(MainViewModel.class).getWeatherForecast().observe(this,this::render);}
 private void render(WeatherForecast w){if(w==null)return;String place=w.getDistrict().isBlank()?w.getCity():w.getDistrict()+" / "+w.getCity();location.setText("Haftalık hava tahmini · "+place);deviceLocation.setText(place);temp.setText(n(w.getCurrentTemperature())+"°C");condition.setText(condition(w.getCurrentWeatherCode()));details.setText("Kaynak: "+sourceLabel(w.getSource())+" · Bahçe çevresi tahmini");humidity.setText("💧\nNem %"+n(w.getCurrentHumidity()));wind.setText("≋\nRüzgâr "+n(w.getCurrentWind())+" km/sa");rain.setText("☂\nYağış %"+n(w.getTodayRainProbability()));pressure.setText("⌁\n"+n(w.getCurrentPressure())+" hPa");icon.setImageResource(icon(w.getCurrentWeatherCode()));chart.setDays(w.getDays());renderDays(w.getDays());renderInsights(w.getDays());advice.setText(advice(w));}
 private void renderDays(List<WeatherDay> list){days.removeAllViews();for(WeatherDay d:list){TextView v=new TextView(this);v.setText(label(d.getDate())+"\n"+iconText(d.getRainProbability())+"\n"+n(d.getTemperatureMax())+"°\n"+n(d.getTemperatureMin())+"°\n💧 %"+n(d.getRainProbability())+"\n≋ "+n(d.getWindMax())+" km/sa");v.setTextSize(12);v.setTextColor(ContextCompat.getColor(this,R.color.textPrimary));v.setGravity(Gravity.CENTER);v.setPadding(dp(12),dp(12),dp(12),dp(12));v.setBackgroundResource(R.drawable.bg_weather_day);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(86),LinearLayout.LayoutParams.WRAP_CONTENT);p.setMarginEnd(dp(8));v.setLayoutParams(p);days.addView(v);}}
 private void renderInsights(List<WeatherDay> l){insights.removeAllViews();WeatherDay hot=null,wet=null;for(WeatherDay d:l){if(hot==null||v(d.getTemperatureMax())>v(hot.getTemperatureMax()))hot=d;if(wet==null||v(d.getRainProbability())>v(wet.getRainProbability()))wet=d;} addInsight("Yağış ihtimali",wet==null?"—":"%"+n(wet.getRainProbability()),"En yağışlı gün");addInsight("En sıcak gün",hot==null?"—":n(hot.getTemperatureMax())+"°C",hot==null?"":""+label(hot.getDate()));}
 private void addInsight(String title,String value,String sub){TextView v=new TextView(this);v.setText(title+"\n"+value+"\n"+sub);v.setTextSize(12);v.setTextColor(ContextCompat.getColor(this,R.color.textPrimary));v.setPadding(dp(14),dp(14),dp(10),dp(14));v.setBackgroundResource(R.drawable.bg_weather_day);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1);p.setMarginEnd(dp(8));v.setLayoutParams(p);insights.addView(v);}
 private String advice(WeatherForecast w){return w.getTomorrowRainProbability()!=null&&w.getTomorrowRainProbability()>=50?"Yarın yağış olasılığı yüksek. Sulama planını uygulamadan önce yeniden kontrol edin.":"Yarın için belirgin yağış riski görünmüyor. Sulama Asistanı nem verisine göre öneri sunmaya devam eder.";} private String sourceLabel(String source){return "openweather".equalsIgnoreCase(source)?"OpenWeather":"Open-Meteo";} private int icon(Long c){if(c!=null&&c>=51)return R.drawable.ic_water_drop_24;if(c!=null&&c>=2)return R.drawable.ic_weather_cloud_24;return R.drawable.ic_weather_sunny_24;} private String iconText(Double r){return r!=null&&r>=50?"☂":"☀";}private String condition(Long c){return c!=null&&c>=51?"Yağışlı":c!=null&&c>=2?"Bulutlu":"Güneşli";}private String n(Double x){return x==null?"—":String.valueOf(Math.round(x));}private double v(Double x){return x==null?-1:x;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private String label(String d){try{return LocalDate.parse(d).format(DateTimeFormatter.ofPattern("EEE\nd MMM",new Locale("tr","TR")));}catch(Exception e){return d;}}
}
